name: Deploy docs
on:
  workflow_dispatch:
  push:
    tags: ["v*"]
    paths:
      - website/**

jobs:
  docs-deployment-production:
    name: Deploy docs
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

        if: steps.changed-files-specific.outputs.any_changed == 'false'
      - run: echo No changes detected, skipping docs deployment