name: Docs Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    branches: ["main", "v*"]
    paths:
      - website/**
      - .github/workflows/preview.yml
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  docs-deployment-preview:
    if: github.event.pull_request.draft == false
    environment: Preview
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## preview deployment
            Changes detected in website directory or preview workflow.
            Deploying new preview site
          comment_tag: docs-preview
          mode: 'recreate'
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}