name: 'NPM version bump'
on:
  pull_request:
    branches: [ main ]
    types:
      - closed
jobs:
  version_bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Version Bump Minor'
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: 'minor'
          commit-message: 'CI: bumps version to {{version}} (minor)'
          target-branch: 'main'

      - name: 'Version Bump Patch'
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: 'patch'
          commit-message: 'CI: bumps version to {{version}} (patch)'
          target-branch: 'main'